nodeLinker: node-modules

packageExtensions:
    '@cratis/arc.react@22.5.0':
        dependencies:
            rxjs: '7.8.2'
    '@primereact/headless@11.1.0':
        dependencies:
            react: '19.2.8'
    '@primereact/styles@11.1.0':
        dependencies:
            '@primeuix/motion': '1.0.0'
    '@primereact/ui@11.1.0':
        dependencies:
            '@primereact/core': '11.1.0'
            react-dom: '19.2.8'
    '@storybook/addon-vitest@10.5.10':
        dependencies:
            react: '19.2.8'
    'storybook@10.5.10':
        dependencies:
            react: '19.2.8'
    'debug@3.2.7':
        dependencies:
            supports-color: '*'
    'debug@4.4.3':
        dependencies:
            supports-color: '*'

pnpMode: loose

compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

yarnPath: .yarn/releases/yarn-4.5.3.cjs
