// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

import typescript from '@rollup/plugin-typescript';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import peerDepsExternal from 'rollup-plugin-peer-deps-external';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join, resolve } from 'path';

/**
 * Rollup plugin that compiles the Tailwind entry CSS through PostCSS after the
 * bundle is written, producing a self-contained tailwind-utilities.css written
 * into both the ESM and CJS output directories.
 *
 * Because Rollup's external rule preserves CSS imports verbatim in the output
 * JS, the `import './tailwind-utilities.css'` added to index.ts will be kept
 * in dist/esm/index.js and dist/cjs/index.js.  Vite (or any bundler) in the
 * consuming app then finds the CSS file sitting next to the JS and injects it
 * automatically — no manual import required in the consumer app.
 *
 * Without this step the utility classes (e.g. p-2, gap-1, w-10 …) only exist
 * in the package's source JSX and would never be generated by the consuming
 * app's own Tailwind build, because node_modules is typically excluded from
 * content scanning.
 */
function compileTailwind(sourceDir, cjsPath, esmPath) {
    let hasRun = false;
    return {
        name: 'compile-tailwind',
        async closeBundle() {
            if (hasRun) return;
            hasRun = true;

            const inputFile = resolve(sourceDir, 'tailwind.css');

            const { default: postcss } = await import('postcss');
            const { default: tailwindcss } = await import('@tailwindcss/postcss');
            const { default: autoprefixer } = await import('autoprefixer');

            const css = readFileSync(inputFile, 'utf8');

            for (const outputDir of [cjsPath, esmPath]) {
                const outputFile = resolve(outputDir, 'tailwind-utilities.css');
                const result = await postcss([tailwindcss({ base: sourceDir }), autoprefixer]).process(css, {
                    from: inputFile,
                    to: outputFile,
                });
                mkdirSync(dirname(outputFile), { recursive: true });
                writeFileSync(outputFile, result.css);
            }
            console.log('✓ Compiled Tailwind utilities → dist/{cjs,esm}/tailwind-utilities.css');
        },
    };
}

/**
 * Rollup plugin to generate package.json files in output directories
 * This ensures proper module resolution for both CJS and ESM formats
 */
function generatePackageJson(cjsPath, esmPath) {
    return {
        name: 'generate-package-json',
        buildEnd() {
            // Create CJS package.json
            const cjsDir = cjsPath;
            mkdirSync(cjsDir, { recursive: true });
            writeFileSync(
                join(cjsDir, 'package.json'),
                JSON.stringify({ type: 'commonjs' }, null, 2),
                'utf-8'
            );

            // Create ESM package.json
            const esmDir = esmPath;
            mkdirSync(esmDir, { recursive: true });
            writeFileSync(
                join(esmDir, 'package.json'),
                JSON.stringify({ type: 'module' }, null, 2),
                'utf-8'
            );

            console.log('✓ Generated package.json files for CJS and ESM outputs');
        }
    };
}

export function rollup(cjsPath, esmPath, tsconfigPath, pkg) {
    const sourceDir = dirname(tsconfigPath);
    return {
        input: 'index.ts',

        output: [
            {
                dir: cjsPath,
                format: "cjs",
                exports: "named",
                sourcemap: true,
                preserveModules: true,
                preserveModulesRoot: "."
            },
            {
                dir: esmPath,
                format: "es",
                exports: "named",
                sourcemap: true,
                preserveModules: true,
                preserveModulesRoot: "."
            }
        ],
        external: [
            ...Object.keys(pkg.dependencies || {}),
            ...Object.keys(pkg.peerDependencies || {}),
            /^@cratis\/components/,
            /^@cratis\/arc/,
            /^primereact\//,
            /^primeicons/,
            /^react-icons\//,
            /\.css$/,
            'react',
            'react-dom',
        ],
        plugins: [
            peerDepsExternal(),
            nodeResolve({
                extensions: ['.mjs', '.js', '.json', '.node', '.ts', '.tsx']
            }),
            typescript({
                tsconfig: false,
                exclude: ["node_modules", "../node_modules", "**/for_*/**/*", "**/when_*/**/*"],
                compilerOptions: {
                    target: "ES2022",
                    module: "ESNext",
                    moduleResolution: "bundler",
                    jsx: "react-jsx",
                    sourceMap: true,
                    importHelpers: false,
                    noCheck: true,
                    declaration: false,
                    declarationMap: false,
                    composite: false,
                }
            }),
            generatePackageJson(cjsPath, esmPath),
            compileTailwind(sourceDir, cjsPath, esmPath),
        ]
    };
}
