// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis — do not edit

/** Stable data-cratis-part names exposed by each public component. */
export const cratisParts = {
    CheckboxField: ['root', 'input', 'box', 'indicator'],
    RatingField: ['root', 'option', 'input', 'star'],
    RadioButtonField: ['root', 'input', 'box', 'indicator'],
    RadioGroupField: ['root', 'option', 'input', 'box', 'indicator'],
    ChipsField: ['root', 'item', 'remove', 'input'],
    ToggleSwitchField: ['root', 'input', 'control', 'handle'],
    SliderField: ['root', 'input', 'value'],
    NumberField: ['root', 'input'],
    ColorPickerField: ['root', 'input', 'value'],
    PasswordField: ['root', 'input', 'toggle'],
    InputTextField: ['input'],
    TextAreaField: ['textarea'],
    Dropdown: ['root', 'value', 'filter', 'trigger', 'clear', 'popover', 'listbox', 'option', 'multiple', 'indicator'],
    DropdownField: ['root', 'value', 'filter', 'trigger', 'clear', 'popover', 'listbox', 'option', 'multiple', 'indicator'],
    MultiSelectField: ['root', 'value', 'filter', 'trigger', 'clear', 'popover', 'listbox', 'option', 'multiple', 'indicator'],
    DatePickerInput: ['root', 'group', 'input', 'segment', 'placeholder', 'trigger', 'popover', 'dialog', 'calendar', 'header', 'previous', 'heading', 'next', 'grid', 'cell', 'button-bar', 'today', 'clear'],
    CalendarField: ['root', 'group', 'input', 'segment', 'placeholder', 'trigger', 'popover', 'dialog', 'calendar', 'header', 'previous', 'heading', 'next', 'grid', 'cell', 'button-bar', 'today', 'clear'],
    Button: ['root', 'spinner', 'icon', 'label'],
    ActionMenubar: ['root', 'spinner', 'icon', 'label'],
    Tooltip: ['trigger', 'popup'],
    Dialog: ['backdrop', 'positioner', 'root', 'header', 'title', 'close', 'content', 'busy-scope', 'footer', 'confirm', 'cancel'],
    CommandDialog: ['backdrop', 'positioner', 'root', 'header', 'title', 'close', 'content', 'busy-scope', 'footer', 'confirm', 'cancel'],
    CommandStepper: ['root', 'list', 'step', 'header', 'number', 'title', 'separator', 'panels', 'panel'],
    DataTableCore: ['root', 'search', 'search-input', 'table-container', 'table', 'head', 'header-row', 'header-cell', 'header-content', 'sort', 'body', 'empty-row', 'empty-cell', 'row', 'cell'],
    DataTableForObservableQuery: ['root', 'search', 'search-input', 'table-container', 'table', 'head', 'header-row', 'header-cell', 'header-content', 'sort', 'body', 'empty-row', 'empty-cell', 'row', 'cell'],
    DataTableForQuery: ['root', 'search', 'search-input', 'table-container', 'table', 'head', 'header-row', 'header-cell', 'header-content', 'sort', 'body', 'empty-row', 'empty-cell', 'row', 'cell'],
    ColumnFilterMenu: ['filter-trigger', 'filter-popover', 'filter-menu', 'filter-actions'],
    TablePaginator: ['root', 'range', 'info'],
    Toaster: ['region', 'toast', 'icon', 'content', 'title', 'description', 'close', 'action'],
    EventsView: ['timeline', 'event', 'separator', 'marker', 'connector', 'content'],
    ChatSidebar: ['backdrop', 'root', 'header', 'back', 'title', 'close', 'content'],
    Toolbar: ['root'],
    ToolbarButton: ['button', 'icon', 'label'],
    ToolbarFolder: ['toolbar-folder', 'toolbar-folder-trigger', 'toolbar-folder-panel'],
    ToolbarFanOutItem: ['fanout-root', 'fanout-trigger', 'fanout-panel'],
    ToolbarSeparator: ['toolbar-separator'],
    ToolbarSection: ['toolbar-section', 'toolbar-context'],
    ToolbarGroup: ['toolbar-group', 'toolbar-slot', 'toolbar-slot-incoming', 'toolbar-slot-outgoing'],
    ToolbarLayout: ['toolbar-layout', 'toolbar-slot', 'toolbar-slot-incoming', 'toolbar-slot-outgoing'],
    Skeleton: ['root'],
    Message: ['root', 'icon', 'text'],
    Badge: ['root'],
    ProgressSpinner: ['root', 'svg', 'track', 'range'],
    Avatar: ['root', 'image', 'fallback'],
    Tag: ['root', 'icon', 'label'],
    ProgressBar: ['root', 'indicator', 'label'],
    Chip: ['root', 'icon', 'label', 'remove'],
} as const;

/** The canonical Components part-name manifest. */
export type CratisPartsManifest = typeof cratisParts;

/** Stable part names exposed by one component in the canonical manifest. */
export type PartsOf<K extends keyof CratisPartsManifest> = CratisPartsManifest[K][number];
