// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

/**
 * The pass-through slots and unstyled DOM markers supported by Components 3 on PrimeReact 11.
 *
 * Slot names are the keys accepted by PrimeReact's component-level `pt` objects. Rendered markers
 * identify the `data-scope` and optional `data-part` emitted by the supported composition.
 * Additions are compatible; removing or renaming an entry requires a new Components major.
 */
export const components3PrimeReact11PassThroughContract = {
    id: '@cratis/components@3/primereact@11/pass-through',
    componentsMajor: 3,
    primeReactMajor: 11,
    revision: 1,
    components: {
        button: {
            globalKey: 'button',
            slots: ['root'],
            renderedMarkers: [{ scope: 'button' }],
        },
        inputtext: {
            globalKey: 'inputtext',
            slots: ['root'],
            renderedMarkers: [{ scope: 'inputtext' }],
        },
        textarea: {
            globalKey: 'textarea',
            slots: ['root'],
            renderedMarkers: [{ scope: 'textarea' }],
        },
        inputnumber: {
            globalKey: 'inputnumber.root',
            slots: ['root', 'input'],
            renderedMarkers: [
                { scope: 'inputnumber', part: 'root' },
                { scope: 'inputnumber', part: 'input' },
            ],
        },
        select: {
            globalKey: 'select.root',
            slots: [
                'root',
                'trigger',
                'value',
                'clear',
                'indicator',
                'positioner',
                'popup',
                'filter',
                'list',
                'option',
            ],
            renderedMarkers: [
                { scope: 'select', part: 'root' },
                { scope: 'select', part: 'trigger' },
                { scope: 'select', part: 'value' },
                { scope: 'select', part: 'clear' },
                { scope: 'select', part: 'indicator' },
                { scope: 'select', part: 'positioner' },
                { scope: 'select', part: 'popup' },
                { scope: 'select', part: 'filter' },
                { scope: 'select', part: 'list' },
                { scope: 'select', part: 'option' },
            ],
        },
        checkbox: {
            globalKey: 'checkbox.root',
            slots: ['root', 'input', 'box', 'indicator'],
            renderedMarkers: [
                { scope: 'checkbox', part: 'root' },
                { scope: 'checkbox', part: 'input' },
                { scope: 'checkboxbox' },
                { scope: 'checkboxindicator' },
            ],
        },
        radiobutton: {
            globalKey: 'radiobutton.root',
            slots: ['root', 'input', 'box', 'indicator'],
            renderedMarkers: [
                { scope: 'radiobutton', part: 'root' },
                { scope: 'radiobutton', part: 'input' },
                { scope: 'radiobutton', part: 'box' },
                { scope: 'radiobutton', part: 'indicator' },
            ],
        },
        datepicker: {
            globalKey: 'datepicker.root',
            slots: [
                'root',
                'trigger',
                'positioner',
                'popup',
                'calendar',
                'header',
                'prev',
                'title',
                'selectMonth',
                'selectYear',
                'next',
                'tableBody',
            ],
            renderedMarkers: [
                { scope: 'datepicker', part: 'root' },
                { scope: 'datepicker', part: 'input' },
                { scope: 'datepicker', part: 'trigger' },
                { scope: 'datepicker', part: 'positioner' },
                { scope: 'datepicker', part: 'popup' },
                { scope: 'datepicker', part: 'calendar' },
                { scope: 'datepicker', part: 'header' },
                { scope: 'datepicker', part: 'prev' },
                { scope: 'datepicker', part: 'title' },
                { scope: 'datepicker', part: 'selectmonth' },
                { scope: 'datepicker', part: 'selectyear' },
                { scope: 'datepicker', part: 'next' },
                { scope: 'datepicker', part: 'table' },
                { scope: 'datepicker', part: 'tablehead' },
                { scope: 'datepicker', part: 'tablebody' },
                { scope: 'datepicker', part: 'time' },
            ],
        },
        slider: {
            globalKey: 'slider.root',
            slots: ['root', 'track', 'range', 'handle'],
            renderedMarkers: [
                { scope: 'slider', part: 'root' },
                { scope: 'slider', part: 'track' },
                { scope: 'slider', part: 'range' },
                { scope: 'slider', part: 'handle' },
            ],
        },
        inputtags: {
            globalKey: 'inputtags.root',
            slots: ['root'],
            renderedMarkers: [{ scope: 'inputtags', part: 'root' }],
        },
        inputcolor: {
            globalKey: 'inputcolor.root',
            slots: [
                'area',
                'areaBackground',
                'areaHandle',
                'sliderTrack',
                'sliderHandle',
                'swatch',
                'swatchBackground',
            ],
            renderedMarkers: [
                { scope: 'inputcolor', part: 'area' },
                { scope: 'inputcolor', part: 'areabackground' },
                { scope: 'inputcolor', part: 'areahandle' },
                { scope: 'inputcolor', part: 'slider' },
                { scope: 'inputcolor', part: 'slidertrack' },
                { scope: 'inputcolor', part: 'sliderhandle' },
                { scope: 'inputcolor', part: 'swatch' },
                { scope: 'inputcolor', part: 'swatchbackground' },
            ],
        },
        timeline: {
            globalKey: 'timeline.root',
            slots: ['root', 'event', 'separator', 'marker', 'connector', 'content'],
            renderedMarkers: [
                { scope: 'timeline', part: 'root' },
                { scope: 'timeline', part: 'event' },
                { scope: 'timeline', part: 'separator' },
                { scope: 'timeline', part: 'marker' },
                { scope: 'timeline', part: 'connector' },
                { scope: 'timeline', part: 'content' },
            ],
        },
        rating: {
            globalKey: 'rating.root',
            slots: ['root', 'option', 'onIcon', 'offIcon'],
            renderedMarkers: [
                { scope: 'rating', part: 'root' },
                { scope: 'rating', part: 'option' },
                { scope: 'rating', part: 'on' },
                { scope: 'rating', part: 'off' },
            ],
        },
        toggleswitch: {
            globalKey: 'toggleswitch.root',
            slots: ['root', 'input', 'control', 'handle'],
            renderedMarkers: [
                { scope: 'toggleswitch', part: 'root' },
                { scope: 'toggleswitch', part: 'control' },
                { scope: 'toggleswitch', part: 'handle' },
            ],
        },
        inputpassword: {
            globalKey: 'inputtext',
            slots: ['root'],
            renderedMarkers: [{ scope: 'inputpassword' }],
        },
        dialog: {
            globalKey: 'dialog.root',
            slots: [
                'backdrop',
                'positioner',
                'popup',
                'header',
                'title',
                'close',
                'content',
                'footer',
            ],
            renderedMarkers: [
                { scope: 'dialog', part: 'backdrop' },
                { scope: 'dialog', part: 'positioner' },
                { scope: 'dialog', part: 'popup' },
                { scope: 'dialog', part: 'header' },
                { scope: 'dialog', part: 'title' },
                { scope: 'dialog', part: 'close' },
                { scope: 'dialog', part: 'content' },
                { scope: 'dialog', part: 'footer' },
            ],
        },
        datatable: {
            globalKey: 'datatable.root',
            slots: [
                'root',
                'tableContainer',
                'table',
                'head',
                'theadRow',
                'theadCell',
                'body',
                'row',
                'cell',
            ],
            renderedMarkers: [
                { scope: 'datatable', part: 'root' },
                { scope: 'datatable', part: 'tablecontainer' },
                { scope: 'datatable', part: 'table' },
                { scope: 'datatable', part: 'thead' },
                { scope: 'datatable', part: 'theadrow' },
                { scope: 'datatable', part: 'theadcell' },
                { scope: 'datatable', part: 'tbody' },
                { scope: 'datatable', part: 'row' },
                { scope: 'datatable', part: 'cell' },
            ],
        },
        stepper: {
            globalKey: 'stepper.root',
            slots: [
                'root',
                'list',
                'step',
                'header',
                'number',
                'title',
                'separator',
                'panels',
                'panel',
            ],
            renderedMarkers: [
                { scope: 'stepper', part: 'root' },
                { scope: 'stepper', part: 'list' },
                { scope: 'stepper', part: 'step' },
                { scope: 'stepper', part: 'header' },
                { scope: 'stepper', part: 'number' },
                { scope: 'stepper', part: 'title' },
                { scope: 'stepper', part: 'separator' },
                { scope: 'stepper', part: 'panels' },
                { scope: 'stepper', part: 'panel' },
            ],
        },
    },
} as const;
